x-comfyui-base: &comfyui-base
  container_name: ComfyUI
  ports:
    - 8188:8188
  volumes:
    - ./models:/app/models
    - ./output:/app/output
  restart: unless-stopped

services:
  # Base (CPU-only) configuration
  comfyui-base:
    <<: *comfyui-base
    build:
      target: base
    image: local/comfyui:latest
    profiles:
      - base

  # CUDA (NVIDIA GPU-enabled) configuration
  comfyui-cuda:
    <<: *comfyui-base
    build:
      target: cuda
    image: local/comfyui:cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - cuda
